"use client";
import React from 'react';
import './globals.css';
import 'antd/dist/antd.css';
import { Inter } from 'next/font/google';
import { Provider } from 'react-redux';
import { persistor, store } from '@/redux-setup/store';
import { PersistGate } from 'redux-persist/integration/react';
import NumberProvider from '@/context/useNumberContext';
import StatusProvider from '@/context/useStatusStateContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Simple Todo App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <PersistGate persistor={persistor}>
            <NumberProvider>
              <StatusProvider>
                {children}
              </StatusProvider>
            </NumberProvider>
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
